<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
	  <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Crimson_AndroidMusicPresence</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <PackageIcon>logo.png</PackageIcon>
    <ApplicationIcon>Android_logo_2019(1).ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Tray_Icons\Tray_Active_USB.ico" />
    <None Remove="Tray_Icons\Tray_Active_WiFi.ico" />
    <None Remove="Tray_Icons\Tray_NoDevice.ico" />
    <None Remove="Tray_Icons\Tray_Scrcpy_USB.ico" />
    <None Remove="Tray_Icons\Tray_Scrcpy_WiFi.ico" />
    <None Remove="Tray_Icons\Tray_WiFi_Noport.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Android_logo_2019(1).ico" />
    <Content Include="Tray_Icons\Tray_Active_USB.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Tray_Icons\Tray_Active_WiFi.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Tray_Icons\Tray_NoDevice.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Tray_Icons\Tray_Scrcpy_USB.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Tray_Icons\Tray_Scrcpy_WiFi.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Tray_Icons\Tray_WiFi_Noport.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Version.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
	</ItemGroup>


	<ItemGroup>
	  <None Update="Resources\adb.exe">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\AdbWinApi.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\AdbWinUsbApi.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\avcodec-61.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\avformat-61.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\avutil-59.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\ffmpeg.exe">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\icon.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\libusb-1.0.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\logo.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Update="Resources\open_a_terminal_here.bat">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\scrcpy-console.bat">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\scrcpy-noconsole.vbs">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\scrcpy-server">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\scrcpy.exe">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\SDL2.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\swresample-5.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
